public class JapanInvokableTriggerApex {
    public static void call(){
       
          String accname='9090 djff sffw';
          String code='9090';
          string concate='';
          List<String> arr=accname.split(' ');
           
        for(integer i=0;i<arr.size();i++){
            if(arr[i].contains(code)){
                
            }
        }
             
            
          System.debug(concate);
    }
}