public class Payment_Mode {
  /*  public static void call(List<Order__c> li){
        List<Order__c> cash=new List<Order__c>();
        List<Order__c> loan=new List<Order__c>();
        
        for(Order__c c: li){
            if(c.Payment_Mode__c == 'Cash'){
                cash.add(c);
            }
            else{
                loan.add(c);
            }
        }
        Integer c=cash.size();
        Integer l=loan.size();
        Product__c p=[select id,Name from Product__c];
        p.By_Cash__c=c;
        p.By_Loan__c=l;
    }
*/
}